export const QUIZ_REQUEST = 'QUIZ_REQUEST';
export const QUIZ_SUCCESS = 'QUIZ_SUCCESS';
export const QUIZ_FAIL = 'QUIZ_FAIL';

export const QUIZ_CHANGE_QUESTION = 'QUIZ_CHANGE_QUESTION';

export const CHANGE_ANSWER = 'CHANGE_ANSWER';
